import type { MapConfig } from '../types'

/**
 * 腾讯 CDN 瓦片基地址。
 * 瓦片版权归腾讯所有，本项目仅用于个人学习 / 非商业用途。
 * URL 规则：{base}/{图层目录}/{z}_{x}_{y}.jpg
 */
const TILE_BASE = 'https://game.gtimg.cn/images/dfm/cp/a20240729directory/img'

/**
 * 攻防模式两张地图配置。
 * 数据来自官网地图工具（df.qq.com/cp/a20240729directory）脚本中的
 * mapScaleInfo：boundsW/boundsH、minZoom/initZoom、initX/initY，
 * 边界换算公式（攻防模式，pixelToLatLngRatio = -1）：
 *   southWest = [0, -80]
 *   northEast = [-(boundsH - 70), -boundsW]
 */
export const MAPS: MapConfig[] = [
  {
    id: 'ascent',
    name: '攀升',
    enName: 'Ascent',
    layerName: 'map_pc',
    tileUrl: `${TILE_BASE}/map_pc/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 5,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-120, 90],
  },
  {
    id: 'flashpoint',
    name: '临界点',
    enName: 'Flashpoint',
    layerName: 'map_ljd_pc',
    tileUrl: `${TILE_BASE}/map_ljd_pc/{z}_{x}_{y}.jpg`,
    minZoom: 3,
    initZoom: 3,
    maxZoom: 8,
    maxNativeZoom: 5,
    boundsW: -250,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 250],
    initCenter: [-120, 105],
  },
  {
    id: 'fault',
    name: '断层',
    enName: 'Fault',
    layerName: 'map_dc',
    tileUrl: `${TILE_BASE}/map_dc/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-125, 105],
  },
  {
    id: 'brokentrack',
    name: '断轨',
    enName: 'BrokenTrack',
    layerName: 'map_dg',
    tileUrl: `${TILE_BASE}/map_dg/{z}_{x}_{y}.jpg`,
    minZoom: 2,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 350,
    southWest: [0, -80],
    northEast: [-280, 300],
    initCenter: [-130, 130],
  },
  {
    id: 'colosseum',
    name: '克劳狄斗兽场',
    enName: 'ClaudiusColosseum',
    layerName: 'map_dsc',
    tileUrl: `${TILE_BASE}/map_dsc/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-115, 110],
  },
  {
    id: 'stormeye',
    name: '风暴眼',
    enName: 'StormEye',
    layerName: 'map_hdz',
    tileUrl: `${TILE_BASE}/map_hdz/{z}_{x}_{y}.jpg`,
    minZoom: 2.6,
    initZoom: 2.6,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-105, 105],
  },
  {
    id: 'ember',
    name: '烬区',
    enName: 'Ember',
    layerName: 'map_jq',
    // 官方总览瓦片与 map_jq 使用相同坐标系，但不含烘焙在普通瓦片中的活动区黑色遮罩。
    tileUrl: `${TILE_BASE}/map_jq_zl/{z}_{x}_{y}.jpg`,
    minZoom: 3,
    initZoom: 3,
    maxZoom: 8,
    maxNativeZoom: 5,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-130, 100],
  },
  {
    id: 'pyramid',
    name: '金字塔',
    enName: 'Pyramid',
    layerName: 'map_jzt',
    tileUrl: `${TILE_BASE}/map_jzt/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-125, 105],
  },
  {
    id: 'trench',
    name: '堑壕战',
    enName: 'TrenchWarfare',
    layerName: 'map_qhz',
    tileUrl: `${TILE_BASE}/map_qhz/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 5,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-130, 110],
  },
  {
    id: 'umuscanal',
    name: '乌姆斯运河',
    enName: 'UmusCanal',
    layerName: 'map_wmsyh',
    tileUrl: `${TILE_BASE}/map_wmsyh/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-115, 110],
  },
  {
    id: 'aftershock',
    name: '余震',
    enName: 'Aftershock',
    layerName: 'map_yz',
    tileUrl: `${TILE_BASE}/map_yz/{z}_{x}_{y}.jpg`,
    minZoom: 2.5,
    initZoom: 2.5,
    maxZoom: 8,
    maxNativeZoom: 4,
    boundsW: -300,
    boundsH: 300,
    southWest: [0, -80],
    northEast: [-230, 300],
    initCenter: [-115, 110],
  },
]

export const MAP_BY_ID: Record<string, MapConfig> = Object.fromEntries(
  MAPS.map((m) => [m.id, m]),
)
